* Re: To My Best Friend:

你是我最好的朋友呢.
至少在遍历了我脑内的所有人中, 不曾有你这么棒的人了.

不要责怪你的记忆, 我也不曾记得我们第一次搭话的契机是什么, 还不熟悉对方一起做了些什么. 若找准一个时间点回忆那时发生的事, 会发现在那之前就已经与你产生某种联系了, 但再往前一些, 又仿佛什么都没有. 空想也最多也只能回忆起一些无关紧要的细节琐事.
我记得, 我小时候 (现在也是) 非常害怕和女生产生接触的, 因为感觉非常的难以预测, 十分复杂且永远无法理解. 后面就只是一味的回避来避免一切麻烦了.
但是你不一样, 我能想起很早就能从你的说话与行为中感受到一种连续性, 让我想要更多的了解你, 有种安心的感觉, 无需顾虑什么只是忠诚于自己意愿就好的, 那种感觉. 现在我很庆幸当时我这样去想了. 若是我的高中生活中, 没有你的陪伴, 我不敢想象会是怎样的一番风景, 大概率我往后的整个人生都会变得一团乱麻吧.

你能在高度内卷的高中教育里自由生活, 面对规矩能问出:"从来如此, 便对么?", 选择的时候能有自己的价值观在里面, 也没有复杂而不可观测的各种 "感情戏" "道德", 能够使用自己所有的技能来达成自己想要的目的. 当众多的选择放到你面前时, 你能进行判断自己想要什么. 遇到自己所知不能解释的现象时, 会去寻求原因, 问询也好, 查资料也好. 寻求过程中遇到一层层的障碍就去一层层解决, 即使那是晦涩难懂的英文文档, 或是充满你从未听说过的术语的面向开发者的帮助指南, 甚至过程中要跟各种垃圾人打交道. 比如不能在手机摄像头上得到满意的画面, 你愿意承受一切的麻烦, 反抗各种限制, 换软件也好, 换系统也好, 硬件不好换去白嫖也好, 来接近自己的目的. 想要成为更好的视频创作者, 利用身边各类资源来改善自己的创作. 要知道, 单单有 "录好的镜头要校色" 这样的念头, 就已经超越了大半的视频创作者了. 我十分的羡慕和景仰你, 你的性格和我的价值观高度统一.

我在教学, 录混的过程中接触的人, 进行平均后的, "普通人" 大概是这个样子的: 他们总是接受着大部分人所用的东西, 从来不清楚自己的需求. 当众多的选项摆在他们面前时, 也是盲目的接受蛊惑, 不进行自己的思考. 当事情最后不是他们想要的样子, 就毫无道理的, 随便找一个发泄的对象责怪起来, 可但凡有人说这其实是好的, 他也改口认为这是好的了.
越是接触更多的人, 就越感觉像你这样有自己的意识的人, 是多么珍贵.

我是个很糟糕的人, 你应该已经十分清楚了. 做事总是虎头蛇尾, 进行很宏大的规划, 过度设计一些事情, 在次要的地方做到过火, 但是事实上发生的从来没想过, 真正想要的全都被别人拿走, 没决定太多事就到了今天. 我求学的过程就是表现之一了, 中考开始, 到出国转高考, 到参加HKUST的自招, 最后高考考砸志愿也报错.
还有就是, 我是优柔寡断做事慢半拍的那种人, 一部分的因为过度分析, 更多的是因为懦弱.
再有最多被诟病的一点就是情商低了, 但是我始终是不知道那个所谓高情商究竟是什么, 所以不做评价了.
这造成了, 如你所见, 我讨厌的生活, 糟糕的人际关系, 糟糕的人生习惯, 甚至糟糕的健康状况.

我真的不值得你所有的称赞, 我不是那么优秀的一个人. 我总是追求那些极端而扭曲的结果. 何时何地都目中无人, 即使自己没有什么实力. 又非常的迟钝, 直到现在我才意识到, 我对其他人的一些"好"让你感到不安了. 就连这封回信都是, 在你的主动要求下才有勇气提笔来写的. 

感谢你这么久以来的款待, 无论是物质上的还是精神上的. 我已经记不清楚, 多少次, 只是因为你在意着, 或是因为你在这个世界上, 让我压抑住了内心深处的黑暗. 没有你, 我必会一头撞上这个垃圾世界, 弄得遍体鳞伤.
你突破各种困难, 放下一切戒备来关心我, 陪我做各种事情, 有好玩的都带上我, 送我礼物, 愿意找我聊天, "监督"我吃饭, 即使是十分无礼的要求你也会答应我, 真的让我非常开心.
我是十分自闭的人, 想来在我高中所结识的有趣的朋友, 大都是通过你才成的. 如段娅朴, 梁晨.
还远不止这些, 能够有一个如此亲近女性的朋友是多么难得, 刚好你还那么可爱, 身边总有很多人在这方面羡慕我, 虽然我尽量的表现出习以为常, 在心里我深知我多么的幸运, 也享受着这份幸运.
你常常来依赖我, 即使是我不可能帮得上忙的东西, 让我非常的安心. 因为能帮得上你, 能和你说说话, 能和你两个人独处, 都让我很开心.
如果可以的话, 以后也请多依赖我一下.

我会努力成为更加值得你称为优秀的人. 这三年想来, 也是这样, 跟着你所打上的些标签一起改变. 即使不尽如人意也成为了我自己.
我会尽力维持一个健康的饮食作息, 你也曾经差点被自己的免疫系统整死过, 现在我也差点被疫苗给干死过, 大概也是知道人命也多脆了, 还懂得了人与人不能一概而论的道理. 这方面还请你放心.
你总是调侃我的外形, 我是十分清楚我既没有天生的质丽也不会打扮自己. 也十分感谢你在这方面的指导, 但我确实没有什么审美观念, 并不觉得这方面我有太多能自己做到的.

我曾经有两个, 朋友.
一个是幼儿园时就结识的, 小时候经常欺负彼此, 但玩的时候能很开心的照顾对方. 小学毕业后, 我面试卷进了自费的民办初中, 她进了学校对口分配的初中, 随后便是我被八中录取, 她去曲靖读了大专. 那时起, 真的就感觉我和她之间产生了一层可悲的, 厚厚的隔膜. 即使爱好上有重叠, 了解对方, 家人间关系不错, 但却已经连基本的交流都保证不了了, 所经历的事差别实在太大了, 往后的关系网也分离开来, 能够一起交流玩耍的机会更是没有了. 就在几周前, 她的18岁生日上, 她和她的家人那仿佛亲切的样子, 她爸爸发了很大的红包给我, 还免费帮我配了一副眼镜, 等等行为, 着实让我难受了很久.
另一个是小学的同学, 自打开始参加各种航模比赛就成立彼此抱团取暖的对象. 到全国各地去比赛的时候住在一起, 平时也成为最亲密的朋友, 没有之一. 到了初中, 他更专注在较为理论性的研究, 我保持着工程师的偏向, 更去做一些比较实际的项目. 那时也互相照应着, 记得在做自己做涡扇喷气发动机的那段时间, 我能够从他那里找到学习与研究的方向, 也把所有测量数据提供给他, 做验证或是经验公式的建模. 但最终还是交集越来越少, 短短过了高中三年就不再频繁联系了.

#+begin_src plain_text
我们义无反顾的试着后悔,
我们声嘶力竭的假装呐喊,
我们万分惋惜的浪费着.
#+end_src

我不希望我与你之间变成这样痛苦的关系, 请以后, 凡是我能够做到的要求都尽管提出. 遇到的事情, 想到的事情, 也能像这样多和我聊聊. 我又比较内向, 可能会不好意思主动联系你, 请以后多和我打打电话微信QQ聊聊天什么的. 有什么好玩的也别落下我 (虽然, 你懂的, 我不保证能每次赴约). 一年至少见两次面, 约好了哦. 还有, 找机会把我介绍给你新认识的朋友吧. 

希望这个回信这蹩脚的中文不会太影响你阅读. 也希望你看着不会难受, 我已尽量以轻松的语言来表达了. 
这里有写的很多话, 因为怕引起更多误解或是引起你的厌恶, 平常也没能说得出口. 但最终还是写了出来, 因为希望对你更坦诚一些. 


顺颂
时祺

Your Friend, *Quan*.
9th Day of 9th Month of 2021
